site_name:        GMMInference.jl
repo_url:         https://github.com/schrimpf/GMMInference.jl
site_description: GMM estimation and inference.
site_author:      Paul Schrimpf
copyright:        Paul Schrimpf

theme: journal

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - smarty
  - toc:
     permalink: True
  - sane_lists
  - admonition
  - footnotes
  - mdx_math

plugins:
  - bibtex:
     bib_file: "jmd/ee.bib"
     cite_style: "pandoc"

docs_dir: 'build'

nav:
  - Package Documentation: index.md
  - Notes and Examples:
    - Estimation: extremumEstimation.md
    - Inference: identificationRobustInference.md
    - Empirical Likelihood: empiricalLikelihood.md
    - Bootstrap: bootstrap.md
  - About:
    - License: license.md
    